{% set version = "7.2" %}
{% set name = "pyobjc-framework-Metal" %}

package:
  name: pyobjc-framework-metal
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c81583d888ef988d29c2952f3bb7a036a3792484c2dc8cdeae3864a1238329d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # pyobjc-core didn't build for PY39 and I am tired of rebuilding it...
  skip: true  # [(not osx) or py2k or python_impl == 'pypy' or (arm64 and py < 39) or (py == 39)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyobjc-core ={{ version }}
    - pyobjc-framework-cocoa ={{ version }}
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.11") }}  # [osx]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - Metal

about:
  home: https://github.com/ronaldoussoren/pyobjc
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Metal framework on macOS
  home: https://bitbucket.org/ronaldoussoren/pyobjc

extra:
  recipe-maintainers:
    - leofang
